AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: N3xFin - Complete AI-Powered Financial Intelligence Platform

Globals:
  Function:
    Timeout: 30
    Runtime: python3.13
    MemorySize: 512
    Environment:
      Variables:
        DYNAMODB_TABLE_USERS: !Ref UsersTable
        DYNAMODB_TABLE_TRANSACTIONS: !Ref TransactionsTable
        DYNAMODB_TABLE_REPORTS: !Ref ReportsTable
        DYNAMODB_TABLE_CONVERSATIONS: !Ref ConversationsTable
        S3_BUCKET: !Ref DataBucket
        COGNITO_USER_POOL_ID: !Ref UserPool
        COGNITO_CLIENT_ID: !Ref UserPoolClient
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
      AllowCredentials: false
    Auth:
      DefaultAuthorizer: CognitoAuthorizer
      AddDefaultAuthorizerToCorsPreflight: false
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !GetAtt UserPool.Arn

Resources:
  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: n3xfin-users
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: n3xfin-client
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      AccessTokenValidity: 30
      IdTokenValidity: 30
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days

  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: n3xfin-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: n3xfin-transactions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: DateIndex
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true

  ReportsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: n3xfin-reports
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

  ConversationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: n3xfin-conversations
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

  # S3 Bucket
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'n3xfin-data-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldStatements
            Status: Enabled
            ExpirationInDays: 365
            Prefix: users/
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  # Auth Lambda Functions
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: n3xfin-register
      CodeUri: src/
      Handler: auth.register.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:SignUp
                - cognito-idp:AdminConfirmSignUp
              Resource: !GetAtt UserPool.Arn
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt UsersTable.Arn
      Events:
        RegisterApi:
          Type: Api
          Properties:
            Path: /auth/register
            Method: POST
            Auth:
              Authorizer: NONE

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: n3xfin-login
      CodeUri: src/
      Handler: auth.login.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:InitiateAuth
                - cognito-idp:AdminInitiateAuth
              Resource: !GetAtt UserPool.Arn
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /auth/login
            Method: POST
            Auth:
              Authorizer: NONE

  VerifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: n3xfin-verify
      CodeUri: src/
      Handler: auth.verify.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:GetUser
              Resource: !GetAtt UserPool.Arn
      Events:
        VerifyApi:
          Type: Api
          Properties:
            Path: /auth/verify
            Method: POST
            Auth:
              Authorizer: NONE

  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: n3xfin-logout
      CodeUri: src/
      Handler: auth.logout.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:GlobalSignOut
              Resource: !GetAtt UserPool.Arn
      Events:
        LogoutApi:
          Type: Api
          Properties:
            Path: /auth/logout
            Method: POST
            Auth:
              Authorizer: NONE

  # Upload Lambda Functions
  GetUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: n3xfin-get-upload-url
      CodeUri: src/
      Handler: upload.get_upload_url.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub '${DataBucket.Arn}/*'
      Events:
        GetUploadUrlApi:
          Type: Api
          Properties:
            Path: /upload/url
            Method: POST

  VerifyUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: n3xfin-verify-upload
      CodeUri: src/
      Handler: upload.verify_upload.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:HeadObject
              Resource: !Sub '${DataBucket.Arn}/*'
      Events:
        VerifyUploadApi:
          Type: Api
          Properties:
            Path: /upload/verify
            Method: POST

  ListFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: n3xfin-list-files
      CodeUri: src/
      Handler: upload.list_files.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !GetAtt DataBucket.Arn
      Events:
        ListFilesApi:
          Type: Api
          Properties:
            Path: /upload/files
            Method: GET

  # Analytics Lambda Functions
  GetAnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: n3xfin-get-analytics
      CodeUri: src/
      Handler: analytics.get_analytics.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:Scan
              Resource:
                - !GetAtt TransactionsTable.Arn
                - !Sub '${TransactionsTable.Arn}/index/*'
      Events:
        GetAnalyticsApi:
          Type: Api
          Properties:
            Path: /analytics
            Method: GET

  SubmitAnomalyFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: n3xfin-submit-anomaly-feedback
      CodeUri: src/
      Handler: analytics.submit_anomaly_feedback.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !GetAtt TransactionsTable.Arn
      Events:
        SubmitAnomalyFeedbackApi:
          Type: Api
          Properties:
            Path: /analytics/anomaly-feedback
            Method: POST

  # Prediction Lambda Functions
  GetPredictionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: n3xfin-get-predictions
      CodeUri: src/
      Handler: prediction.get_predictions.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - !GetAtt TransactionsTable.Arn
                - !Sub '${TransactionsTable.Arn}/index/*'
      Events:
        GetPredictionsApi:
          Type: Api
          Properties:
            Path: /predictions
            Method: GET

  GetAlertsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: n3xfin-get-alerts
      CodeUri: src/
      Handler: prediction.get_alerts.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - !GetAtt TransactionsTable.Arn
                - !Sub '${TransactionsTable.Arn}/index/*'
      Events:
        GetAlertsApi:
          Type: Api
          Properties:
            Path: /predictions/alerts
            Method: GET

  # Recommendation Lambda Functions
  GetRecommendationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: n3xfin-get-recommendations
      CodeUri: src/
      Handler: recommendation.get_recommendations.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
              Resource:
                - !GetAtt TransactionsTable.Arn
                - !Sub '${TransactionsTable.Arn}/index/*'
      Events:
        GetRecommendationsApi:
          Type: Api
          Properties:
            Path: /recommendations
            Method: GET

  # Report Lambda Functions
  GenerateReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: n3xfin-generate-report
      CodeUri: src/
      Handler: report.generate_report.lambda_handler
      Timeout: 60
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:PutItem
              Resource:
                - !GetAtt TransactionsTable.Arn
                - !GetAtt ReportsTable.Arn
                - !Sub '${TransactionsTable.Arn}/index/*'
      Events:
        GenerateReportApi:
          Type: Api
          Properties:
            Path: /reports/generate
            Method: POST

  # Conversation Lambda Function
  AskQuestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: n3xfin-ask-question
      CodeUri: src/
      Handler: conversation.ask_question.lambda_handler
      Timeout: 60
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:PutItem
              Resource:
                - !GetAtt TransactionsTable.Arn
                - !GetAtt ConversationsTable.Arn
                - !Sub '${TransactionsTable.Arn}/index/*'
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
      Events:
        AskQuestionApi:
          Type: Api
          Properties:
            Path: /conversation/ask
            Method: POST

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
  
  ApiId:
    Description: API Gateway ID
    Value: !Ref ServerlessRestApi
  
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
  
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
  
  DataBucketName:
    Description: S3 Data Bucket Name
    Value: !Ref DataBucket
